export type TopicNode = {
  id: string;
  label: string;
  emoji: string;
  difficulty: 1 | 2 | 3;
  prerequisites: string[];
  nextTopics: string[];
  relatedTopics: string[];
  courses: { kunal?: boolean; apna?: boolean; harry?: boolean };
};

const ALL = { kunal: true, apna: true, harry: true } as const;
const KH = { kunal: true, harry: true } as const;

export const TOPIC_GRAPH: Record<string, TopicNode> = {
  complexity: {
    id: "complexity",
    label: "Time & Space Complexity",
    emoji: "⏱️",
    difficulty: 1,
    prerequisites: [],
    nextTopics: ["arrays"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  arrays: {
    id: "arrays",
    label: "Arrays",
    emoji: "📊",
    difficulty: 1,
    prerequisites: [],
    nextTopics: ["searching", "sorting", "strings", "hashing"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  searching: {
    id: "searching",
    label: "Searching",
    emoji: "🔍",
    difficulty: 1,
    prerequisites: ["arrays"],
    nextTopics: ["sorting"],
    relatedTopics: ["arrays"],
    courses: { ...ALL },
  },
  sorting: {
    id: "sorting",
    label: "Sorting",
    emoji: "📶",
    difficulty: 2,
    prerequisites: ["arrays"],
    nextTopics: ["recursion"],
    relatedTopics: ["searching"],
    courses: { ...ALL },
  },
  strings: {
    id: "strings",
    label: "Strings",
    emoji: "🔤",
    difficulty: 1,
    prerequisites: ["arrays"],
    nextTopics: ["hashing", "dp"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  hashing: {
    id: "hashing",
    label: "Hashing",
    emoji: "🧮",
    difficulty: 2,
    prerequisites: ["arrays"],
    nextTopics: ["graphs"],
    relatedTopics: ["strings"],
    courses: { ...ALL },
  },
  recursion: {
    id: "recursion",
    label: "Recursion",
    emoji: "🔁",
    difficulty: 2,
    prerequisites: ["arrays"],
    nextTopics: ["backtracking", "trees", "dp"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  backtracking: {
    id: "backtracking",
    label: "Backtracking",
    emoji: "↩️",
    difficulty: 3,
    prerequisites: ["recursion"],
    nextTopics: ["dp"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  "linked-list": {
    id: "linked-list",
    label: "Linked List",
    emoji: "🔗",
    difficulty: 2,
    prerequisites: ["arrays"],
    nextTopics: ["stack", "queue", "trees"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  stack: {
    id: "stack",
    label: "Stack",
    emoji: "🥞",
    difficulty: 2,
    prerequisites: ["linked-list"],
    nextTopics: ["trees"],
    relatedTopics: ["queue"],
    courses: { ...ALL },
  },
  queue: {
    id: "queue",
    label: "Queue",
    emoji: "🚶",
    difficulty: 2,
    prerequisites: ["linked-list"],
    nextTopics: ["graphs", "trees"],
    relatedTopics: ["stack"],
    courses: { ...ALL },
  },
  trees: {
    id: "trees",
    label: "Trees",
    emoji: "🌳",
    difficulty: 2,
    prerequisites: ["recursion", "linked-list"],
    nextTopics: ["bst", "heap", "segment-tree"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  bst: {
    id: "bst",
    label: "Binary Search Tree",
    emoji: "🌲",
    difficulty: 2,
    prerequisites: ["trees"],
    nextTopics: ["avl"],
    relatedTopics: [],
    courses: { ...KH },
  },
  heap: {
    id: "heap",
    label: "Heap",
    emoji: "⛰️",
    difficulty: 3,
    prerequisites: ["trees"],
    nextTopics: ["greedy"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  graphs: {
    id: "graphs",
    label: "Graphs",
    emoji: "🕸️",
    difficulty: 3,
    prerequisites: ["trees", "queue", "stack"],
    nextTopics: ["shortest-path", "topo-sort"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  dp: {
    id: "dp",
    label: "Dynamic Programming",
    emoji: "🧩",
    difficulty: 3,
    prerequisites: ["recursion", "arrays"],
    nextTopics: ["advanced-dp"],
    relatedTopics: [],
    courses: { ...ALL },
  },
  trie: {
    id: "trie",
    label: "Trie",
    emoji: "🌿",
    difficulty: 3,
    prerequisites: ["trees", "hashing"],
    nextTopics: [],
    relatedTopics: [],
    courses: { ...KH },
  },
  greedy: {
    id: "greedy",
    label: "Greedy",
    emoji: "💰",
    difficulty: 3,
    prerequisites: ["arrays", "heap"],
    nextTopics: [],
    relatedTopics: [],
    courses: { ...ALL },
  },
};

export function matchTopic(lectureTitle: string): TopicNode | null {
  const lower = lectureTitle.toLowerCase();
  const keywords: [string, string][] = [
    ["complexity", "complexity"],
    ["big o", "complexity"],
    ["array", "arrays"],
    ["search", "searching"],
    ["binary search tree", "bst"],
    ["bst", "bst"],
    ["sort", "sorting"],
    ["string", "strings"],
    ["hash", "hashing"],
    ["backtrack", "backtracking"],
    ["recursion", "recursion"],
    ["recursive", "recursion"],
    ["linked list", "linked-list"],
    ["linkedlist", "linked-list"],
    ["stack", "stack"],
    ["queue", "queue"],
    ["trie", "trie"],
    ["heap", "heap"],
    ["priority queue", "heap"],
    ["graph", "graphs"],
    ["dynamic prog", "dp"],
    ["dp", "dp"],
    ["greedy", "greedy"],
    ["tree", "trees"],
  ];
  for (const [kw, id] of keywords) {
    if (lower.includes(kw)) return TOPIC_GRAPH[id] ?? null;
  }
  return null;
}
