// Local source of truth for CodeWithHarry content.
// Generated by `node scripts/sync-harry-content.mjs` using the YouTube API +
// CodeWithHarry_Complete_Curriculum_Architecture.xlsx. The runtime never calls
// the YouTube API directly — re-run the sync script when content changes.

import meta from "./harry-metadata.generated.json";

export type HarryNote = { label: string; url: string };
export type HarryLecture = {
  id: string;
  index: number;
  videoId: string;
  title: string;
  topicId: string;
  duration?: string;
  notes: HarryNote[];
};
export type HarryTopic = { id: string; title: string; emoji: string };

export type HarryTrack = "java" | "cpp" | "dsa";
export type HarryWing = "java" | "cpp";

type TrackData = { topics: HarryTopic[]; lectures: HarryLecture[] };

const TRACKS = meta.tracks as Record<HarryTrack, TrackData>;

export const HARRY_GENERATED_AT = meta.generatedAt as string;

export function getTrackData(track: HarryTrack): TrackData {
  return TRACKS[track];
}

/** Returns Core (Java or C++) topics + lectures with DSA appended as its
 *  own grouping. Topic IDs are prefixed to keep core/DSA disjoint. */
export function getWingData(wing: HarryWing): TrackData {
  const core = TRACKS[wing];
  const dsa = TRACKS.dsa;
  const dsaTopicIdMap = new Map(dsa.topics.map((t) => [t.id, `wing-${t.id}`]));
  const dsaTopics: HarryTopic[] = dsa.topics.map((t) => ({
    ...t,
    id: dsaTopicIdMap.get(t.id)!,
    title: `DSA · ${t.title}`,
  }));
  const dsaLectures: HarryLecture[] = dsa.lectures.map((l) => ({
    ...l,
    topicId: dsaTopicIdMap.get(l.topicId) ?? l.topicId,
  }));
  return {
    topics: [...core.topics, ...dsaTopics],
    lectures: [...core.lectures, ...dsaLectures],
  };
}

/** Lectures that have at least one note/resource link. */
export function getLecturesWithNotes(track: HarryTrack): HarryLecture[] {
  return TRACKS[track].lectures.filter((l) => l.notes.length > 0);
}
